### ISSUE TITLE
F2 is reserved for renaming layer

### ISSUE THREAD

**Issue by saberraz** [mtravis/gridref-qgis#11]
When the plugin is activated, F2 causes crash.

It is best to use shortcut keys not reserved for main QGIS functions.

Thanks
Saber

**Comment by mtravis** [comment]
I'll just remove the shortcut key function altogether as I don't think its
needed.

**Comment by mtravis** [comment]
https://github.com/mtravis/gridref-qgis/commit/b0b2d068393baf85fb7282ab5668c769e4b3d139
