### ISSUE TITLE
Lat/long - reporting

### ISSUE THREAD

**Issue by saberraz** [mtravis/gridref-qgis#7]
Can we have the lat/long in the dialog box that results from the users clicking the map.

**Comment by PeterPetrik** [comment]
@mtravis Are there any outstanding issues with the implementation or this issue can be closed?

**Comment by mtravis** [comment]
I've tested the update but can't see any changes. Has the UI been updated too?

**Comment by PeterPetrik** [comment]
the long/lat is shown where the maptool is used (clicked on the map, shown in pop-up dialog).

**Comment by mtravis** [comment]
I know how to use it but honestly seeing any changes in UI. 

I have tried both installing through QGIS and downloading the zip and placing in plugins directory.

Have you got screenshots of what it look like in QGIS?

**Comment by saberraz** [comment]
Here is a screenshot:
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/108735/2369306/BAkdam6XagKPAfO/gridref-qgis.avi

**Comment by mtravis** [comment]
It's working now my end. Looks great. 

Cheers Peter!
